module.exports = [
    "steancomunnity.ru",
    "stearncomminuty.ru",
    "steamcommunytu.ru",
    "steancommity.com",
    "steamcommnuntiy.com",
    "xrolling",
    "I have become the publisher",
    "swiningblade.com",
    "newlinespoof",
    "bit.ly/Discord-Nitro-Gen-V2",
    "bit.ly/Discord--Nitro-Generator",
    "bitremex.com",
    "store-stempowered.com",
    "steancommunytiu.ru",
    "streammcomunittty.ru",
    "streammcomuunity.ru",
    "steamcommurnuity.com",
    "dlscord.shop",
    "steamcomminutiu.ru",
    "steamcommunlilty.com",
    "/tradeoffer/",
    "/tradeoffers/",
    "stearncormmunity.com",
    "freenitro",
    "discordgivenitro.com"
]